"use client";
import TopHeader from "../../components/_App/TopHeader";
import NavbarVertical from "../../components/Dashboard/Layout/NavbarVertical";
import menuItemsForSecretary from '../../components/Dashboard/Layout/routes/menuItems-secretary.json'
import DashboardHeader from "../../components/Dashboard/Layout/DashboardHeader";
import { useState } from "react";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function SecretaryLaout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [controlNavbar, setControlNavbar] = useState(false);

  return (
    <section>

      <div className={controlNavbar ? "dashboard active" : "dashboard"}>
        <NavbarVertical controlNavbar={controlNavbar} menuItems={menuItemsForSecretary} />

        <div className="dash-page-content">
          <DashboardHeader
            controlNavbar={controlNavbar}
            setControlNavbar={setControlNavbar}
          />
          <div className="mt-5 px-4 container-fluid">{children}</div>
        </div>
      </div>
    </section>
  );
}
