import TopHeader from '../../components/No-ssr/no-ssr-TopHeader'
import Navbar from '../../components/No-ssr/no-ssr-navbar'
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <TopHeader />

      <Navbar />

      <body>{children}</body>
    </html>
  );
}
